[package]
name = "fundsp"
description = "Audio processing and synthesis library."
keywords = ["dsp", "audio"]
license = "MIT OR Apache-2.0"
version = "0.3.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
homepage = "https://github.com/SamiPerttu/fundsp"
repository = "https://github.com/SamiPerttu/fundsp"
readme = "README.md"
edition = "2021"

[dependencies]
generic-array = "0.14.5"
numeric-array = "0.5.2"
num-complex = "0.4.0"
rustfft = "6.0.1"
lazy_static = "1.4.0"
tinyvec = { version = "1.5.1", features = ["alloc"] }
rsor = "0.1.3"

[dev-dependencies]
cpal = "0.13.5"
anyhow = "1.0.53"

[features]
default = []

[[example]]
name = "beep"
path = "examples/beep.rs"

[[example]]
name = "peek"
path = "examples/peek.rs"

[[example]]
name = "sequence"
path = "examples/sequence.rs"

[[example]]
name = "type"
path = "examples/type.rs"
